version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    target-branch: "2.x"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
