name: "PHPStan"

on:
  - push
  - pull_request

permissions:
  contents: read

env:
  COMPOSER_ROOT_VERSION: dev-main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: "PHPStan"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.1"
          - latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          extensions: mongodb, redis, amqp

      - name: Add require for mongodb/mongodb to make tests runnable
        run: "composer require $COMPOSER_FLAGS mongodb/mongodb --dev --no-update"

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          dependency-versions: highest

      - name: Run PHPStan
        run: composer phpstan
